# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='hood',
            name='occupants_count',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Text',
            field=models.TextField(null=True),
        ),
    ]
