# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20181021_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hood',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoods', to='hood.Profile'),
        ),
    ]
