# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_auto_20181023_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Tell us something'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(default='Your Name'),
        ),
    ]
