# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_auto_20181023_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='b_owner',
            field=models.CharField(max_length=20),
        ),
    ]
